### ISSUE TITLE
todo api

### ISSUE THREAD

**Issue by PolarBearAndrew** [PolarBearAndrew/KeepGoing#23]
- [x] GET `/api/v1/todo`
- [x] POST `/api/v1/todo`
- [x] PUT `/api/v1/todo/:id/`
- [x] PUT `/api/v1/todo/:id/complete`
- [x] DELETE `/api/v1/todo/:id`
